<?php

namespace Click\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    
    public function getGalleries()
    {
    	$qb = $this->createQueryBuilder('g')
                   ->select('g');  
    	
    	return $qb->getQuery()->getResult();    	
    }
    
}