<?php

namespace Click\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    
    public function getPhotos()
    {
    	$qb = $this->createQueryBuilder('p')
                   ->select('p');  
    	
    	return $qb->getQuery()->getResult();    	
    }
    
}